spring:
  application:
    name: backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/portfolio}
    username: ${SPRING_DATASOURCE_USERNAME:portfolio}
    password: ${SPRING_DATASOURCE_PASSWORD:portfolio}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true